import {
  Activity,
  Award,
  Check,
  CheckCircle,
  Clock,
  Facebook,
  Heart,
  Instagram,
  Mail,
  MapPin,
  Phone,
  PlusCircle,
  Quote,
  Shield,
  Twitter,
} from "lucide-react"

export const Icons = {
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  plusCircle: PlusCircle,
  mail: Mail,
  phone: Phone,
  heart: Heart,
  award: Award,
  clock: Clock,
  mapPin: MapPin,
  shield: Shield,
  activity: Activity,
  checkCircle: CheckCircle,
  quote: Quote,
  check: Check,
}
